"""create v0.2 data model

Revision ID: 46dbf8c627a1
Revises: 
Create Date: 2026-09-10 00:12:29.799825
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '46dbf8c627a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index('ix_candidates_email', 'candidates', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RECRUITER', name='userrole', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'SCREENING', 'COMPLETED', 'ARCHIVED', name='jobstatus', create_constraint=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_jobs_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_created_by', 'jobs', ['created_by'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'COMPLETED', 'FAILED', name='applicationstatus', create_constraint=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('screening_status', sa.Enum('NOT_STARTED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='screeningstatus', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_applications_candidate_id_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index('ix_applications_candidate_id', 'applications', ['candidate_id'], unique=False)
    op.create_index('ix_applications_job_id', 'applications', ['job_id'], unique=False)
    op.create_index('ix_applications_screening_status', 'applications', ['screening_status'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('REQUIRED', 'PREFERRED', name='requirementpriority', create_constraint=True), nullable=False),
    sa.Column('minimum_years', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_expectations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_requirements_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements'))
    )
    op.create_index('ix_requirements_job_id', 'requirements', ['job_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('MET', 'PARTIALLY_MET', 'UNSUPPORTED', 'NOT_FOUND', name='assessmentstatus', create_constraint=True), nullable=False),
    sa.Column('evidence_strength', sa.Enum('STRONG', 'MODERATE', 'WEAK', 'NONE', name='evidencestrength', create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('claim_summary', sa.Text(), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_assessments_ck_assessments_confidence_range')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_assessments_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_assessments_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments')),
    sa.UniqueConstraint('application_id', 'requirement_id', name='uq_assessments_application_requirement')
    )
    op.create_index('ix_assessments_application_id', 'assessments', ['application_id'], unique=False)
    op.create_index('ix_assessments_requirement_id', 'assessments', ['requirement_id'], unique=False)
    op.create_table('candidate_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('required_coverage', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('preferred_coverage', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('evidence_quality', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tradeoffs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation', sa.Enum('STRONG_MATCH', 'GOOD_MATCH', 'MIXED_MATCH', 'WEAK_MATCH', name='recommendation', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('evidence_quality >= 0 AND evidence_quality <= 1', name=op.f('ck_candidate_assessments_ck_candidate_assessments_evidence_quality_range')),
    sa.CheckConstraint('preferred_coverage >= 0 AND preferred_coverage <= 1', name=op.f('ck_candidate_assessments_ck_candidate_assessments_preferred_coverage_range')),
    sa.CheckConstraint('required_coverage >= 0 AND required_coverage <= 1', name=op.f('ck_candidate_assessments_ck_candidate_assessments_required_coverage_range')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_candidate_assessments_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_assessments')),
    sa.UniqueConstraint('application_id', name='uq_candidate_assessments_application')
    )
    op.create_index('ix_candidate_assessments_application_id', 'candidate_assessments', ['application_id'], unique=False)
    op.create_table('candidate_rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('ranking_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tradeoffs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rank > 0', name=op.f('ck_candidate_rankings_ck_candidate_rankings_rank_positive')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_candidate_rankings_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_candidate_rankings_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_rankings')),
    sa.UniqueConstraint('job_id', 'application_id', name='uq_candidate_rankings_job_application')
    )
    op.create_index('ix_candidate_rankings_job_id', 'candidate_rankings', ['job_id'], unique=False)
    op.create_index('ix_candidate_rankings_job_rank', 'candidate_rankings', ['job_id', 'rank'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('RESUME', 'COVER_LETTER', 'OTHER', name='documenttype', create_constraint=True), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_documents_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_application_id', 'documents', ['application_id'], unique=False)
    op.create_table('pool_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('strong_count', sa.Integer(), nullable=False),
    sa.Column('moderate_count', sa.Integer(), nullable=False),
    sa.Column('weak_count', sa.Integer(), nullable=False),
    sa.Column('unsupported_count', sa.Integer(), nullable=False),
    sa.Column('not_found_count', sa.Integer(), nullable=False),
    sa.Column('coverage_rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('gap_level', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='gaplevel', create_constraint=True), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('candidate_count >= 0', name=op.f('ck_pool_gaps_ck_pool_gaps_candidate_count_nonnegative')),
    sa.CheckConstraint('coverage_rate >= 0 AND coverage_rate <= 1', name=op.f('ck_pool_gaps_ck_pool_gaps_coverage_rate_range')),
    sa.CheckConstraint('moderate_count >= 0', name=op.f('ck_pool_gaps_ck_pool_gaps_moderate_count_nonnegative')),
    sa.CheckConstraint('not_found_count >= 0', name=op.f('ck_pool_gaps_ck_pool_gaps_not_found_count_nonnegative')),
    sa.CheckConstraint('strong_count >= 0', name=op.f('ck_pool_gaps_ck_pool_gaps_strong_count_nonnegative')),
    sa.CheckConstraint('unsupported_count >= 0', name=op.f('ck_pool_gaps_ck_pool_gaps_unsupported_count_nonnegative')),
    sa.CheckConstraint('weak_count >= 0', name=op.f('ck_pool_gaps_ck_pool_gaps_weak_count_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_pool_gaps_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_pool_gaps_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pool_gaps')),
    sa.UniqueConstraint('job_id', 'requirement_id', name='uq_pool_gaps_job_requirement')
    )
    op.create_index('ix_pool_gaps_job_id', 'pool_gaps', ['job_id'], unique=False)
    op.create_index('ix_pool_gaps_requirement_id', 'pool_gaps', ['requirement_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_document_chunks_ck_document_chunks_chunk_index_nonnegative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    op.create_index('ix_document_chunks_document_chunk_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index('ix_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Enum('SKILL', 'EXPERIENCE', 'EDUCATION', 'CERTIFICATION', 'PROJECT', 'RESPONSIBILITY', 'OTHER', name='claimtype', create_constraint=True), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_claims_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], name=op.f('fk_claims_source_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index('ix_claims_application_id', 'claims', ['application_id'], unique=False)
    op.create_index('ix_claims_source_chunk_id', 'claims', ['source_chunk_id'], unique=False)
    op.create_table('claim_requirement_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.Enum('DIRECT', 'EQUIVALENT', 'RELATED', 'WEAKLY_RELATED', name='linkrelationship', create_constraint=True), nullable=False),
    sa.Column('similarity', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('similarity IS NULL OR (similarity >= 0 AND similarity <= 1)', name=op.f('ck_claim_requirement_links_ck_claim_requirement_links_similarity_range')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_requirement_links_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_claim_requirement_links_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_requirement_links')),
    sa.UniqueConstraint('claim_id', 'requirement_id', name='uq_claim_requirement_links_claim_requirement')
    )
    op.create_index('ix_claim_requirement_links_claim_id', 'claim_requirement_links', ['claim_id'], unique=False)
    op.create_index('ix_claim_requirement_links_requirement_id', 'claim_requirement_links', ['requirement_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Enum('DIRECT', 'INDIRECT', 'PROJECT', 'PROFESSIONAL', 'ACADEMIC', 'CERTIFICATION', 'OTHER', name='evidencetype', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_evidence_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_evidence_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_evidence_requirement_id_requirements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], name=op.f('fk_evidence_source_chunk_id_document_chunks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index('ix_evidence_application_id', 'evidence', ['application_id'], unique=False)
    op.create_index('ix_evidence_requirement_id', 'evidence', ['requirement_id'], unique=False)
    op.create_index('ix_evidence_source_chunk_id', 'evidence', ['source_chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_source_chunk_id', table_name='evidence')
    op.drop_index('ix_evidence_requirement_id', table_name='evidence')
    op.drop_index('ix_evidence_application_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_claim_requirement_links_requirement_id', table_name='claim_requirement_links')
    op.drop_index('ix_claim_requirement_links_claim_id', table_name='claim_requirement_links')
    op.drop_table('claim_requirement_links')
    op.drop_index('ix_claims_source_chunk_id', table_name='claims')
    op.drop_index('ix_claims_application_id', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_document_chunks_document_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_chunk_index', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_pool_gaps_requirement_id', table_name='pool_gaps')
    op.drop_index('ix_pool_gaps_job_id', table_name='pool_gaps')
    op.drop_table('pool_gaps')
    op.drop_index('ix_documents_application_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_candidate_rankings_job_rank', table_name='candidate_rankings')
    op.drop_index('ix_candidate_rankings_job_id', table_name='candidate_rankings')
    op.drop_table('candidate_rankings')
    op.drop_index('ix_candidate_assessments_application_id', table_name='candidate_assessments')
    op.drop_table('candidate_assessments')
    op.drop_index('ix_assessments_requirement_id', table_name='assessments')
    op.drop_index('ix_assessments_application_id', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index('ix_requirements_job_id', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('ix_applications_screening_status', table_name='applications')
    op.drop_index('ix_applications_job_id', table_name='applications')
    op.drop_index('ix_applications_candidate_id', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_created_by', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_candidates_email', table_name='candidates')
    op.drop_table('candidates')
    for enum_name in (
        'userrole', 'jobstatus', 'applicationstatus', 'screeningstatus', 'requirementpriority',
        'assessmentstatus', 'evidencestrength', 'recommendation', 'documenttype', 'gaplevel',
        'claimtype', 'linkrelationship', 'evidencetype',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
    # ### end Alembic commands ###
