"""add v0.5 ingestion metadata

Revision ID: e116ecc0f691
Revises: 46dbf8c627a1
Create Date: 2026-09-10 02:06:55.997174
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e116ecc0f691'
down_revision: Union[str, None] = '46dbf8c627a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ingestion_status = sa.Enum('NOT_STARTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='ingestionstatus', create_constraint=True)
    ingestion_status.create(op.get_bind(), checkfirst=True)
    op.add_column('applications', sa.Column('ingestion_status', ingestion_status, server_default='NOT_STARTED', nullable=False))
    op.create_index('ix_applications_ingestion_status', 'applications', ['ingestion_status'], unique=False)
    op.add_column('documents', sa.Column('storage_path', sa.String(length=500), server_default='', nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('sha256', sa.String(length=64), server_default='', nullable=False))
    op.alter_column('applications', 'ingestion_status', server_default=None)
    op.alter_column('documents', 'storage_path', server_default=None)
    op.alter_column('documents', 'file_size', server_default=None)
    op.alter_column('documents', 'sha256', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'sha256')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'storage_path')
    op.drop_index('ix_applications_ingestion_status', table_name='applications')
    op.drop_column('applications', 'ingestion_status')
    op.execute(sa.text('DROP TYPE IF EXISTS ingestionstatus'))
    # ### end Alembic commands ###
